#!/bin/bash
# A dmenu wrapper script for system functions.

cmds="\
lock 		slock
exit 		kill -TERM $(pidof -s dwm)
hibernate 	doas ZZZ
suspend 	doas zzz
reboot		doas reboot
shutdown	doas poweroff"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu )" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`

