#!/bin/sh

# This is bound to Shift+PrintScreen by default, requires maim. It lets you
# choose the kind of screenshot to take, including copying the image or even
# highlighting an area to copy. scrotcucks on suicidewatch right now.

case "$(printf "a selected area\\nfull screen\\na selected area (copy)\\nfull screen (copy)" | dmenu -l 6 -p "Screenshot which area?")" in
	"a selected area") maim -s pic-selected-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"full screen") maim pic-full-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"a selected area (copy)") maim -s | xclip -selection clipboard -t image/png ;;
	"full screen (copy)") maim | xclip -selection clipboard -t image/png ;;
esac

