#!/bin/sh

# This is bound to Shift+PrintScreen by default, requires maim. It lets you
# choose the kind of screenshot to take, including copying the image or even
# highlighting an area to copy. scrotcucks on suicidewatch right now.

case "$(printf "active window\\na selected area\\nfull screen" | dmenu -l 6 -p "Screenshot which area?")" in
	"a selected area") maim -s | xclip -selection clipboard -t image/png ;;
	"full screen") maim | xclip -selection clipboard -t image/png ;;
	"active window") maim -i $(xdotool getactivewindow) | xclip -selection clipboard -t image/png ;;
esac

